### ISSUE TITLE
Migrate content files from existing site.

### ISSUE THREAD

**Issue by bwklein** [thegooddocsproject/website-hugo#9]
This is a high-level tracking case that will close when all migration issues are closed.

### List of Pages to Migrate

- [x] Code of Conduct (maybe from another source) #21 
- [x] Contribute (maybe from another source) #22 
- [x] Licenses  (maybe from another source) #24 
- [x] About #27 
- [x] Community #11 
- [x] Contact #12 
- [x] Decisions #13
- [x] Decision Log #23 
- [x] Home (index) #14 
- [x] Information Architecture Guide #16 
- [x] Press #15 
- [x] Prioritization #17 
- [x] Proposal Selection #18 
- [x] Roles #19 
- [x] Who We Are #20

**Comment by bwklein** [comment]
- [ ] About
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by bwklein** [comment]
All primary content migrated.
